services:
  tcg-tryon:
    build: .
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tcg-tryon.entrypoints=https'
      - 'traefik.http.routers.tcg-tryon.rule=Host(`tryon.tcglabs.id`)'
      - 'traefik.http.routers.tcg-tryon.tls=true'
      - 'traefik.http.services.tcg-tryon.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true
