services:
  nuryanti-gims:
    build: .
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nuryanti-gims.entrypoints=https'
      - 'traefik.http.routers.nuryanti-gims.rule=Host(`tryon.tcglabs.id`)'
      - 'traefik.http.routers.nuryanti-gims.tls=true'
      - 'traefik.http.services.nuryanti-gims.loadbalancer.server.port=3000'

networks:
  proxy:
    external: true
